Add models, controllers and tests
Vanchey359/java-filmorate pull request #2
Opened 2023-01-29 10:53 UTC by Vanchey359

Добавил модели, контроллеры к ним, написал тесты. В постмане все проходит.
Первый пул реквест завалил проверку гита из за 17той версии jdk, сейчас поменял в pom.xml все под 11, надеюсь пройдет :)

2023-01-29 17:25 UTC, kalitva requested changes

2023-01-29 17:25 UTC, kalitva commented on pom.xml
> +        </dependency>
Форматируй файл пробелами вместо табов, это можно сделать в несколько кликов в intellij

2023-01-29 17:25 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
Форматируй пробелами

2023-01-29 17:25 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Получен список всех фильмов");
Логирование только на английском

2023-01-29 17:25 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final List<Film> films = new ArrayList<>();
Используй хэшмап для хранения фильмов, как мы делали в прошлых спринтах

2023-01-29 17:25 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            if (fl.getId() == film.getId()) {
Нужно будет использовать `Map#contains` чтобы выяснить, есть ли уже такой фильм

2023-01-29 17:25 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName() == null || film.getName().isBlank()) {
Это валидация уже делается посредством аннотации `@NotBlank`, здесь вручную проверять нет необходимости

2023-01-29 17:25 UTC, kalitva commented on pom.xml
> +		<relativePath/> <!-- lookup parent from repository -->
Удали коммент

2023-01-29 17:25 UTC, kalitva commented on pom.xml
> +
Зачем здесь пустая линия?

2023-01-29 17:25 UTC, kalitva commented on pom.xml
> +			<groupId>jakarta.validation</groupId>
Выше уже есть эта же зависимость, эту декларацию удали, в импортах пакет `jakarta` замени на `javax`. Не забудь обновить мавен в intellij

2023-01-29 17:25 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getDescription().length() > 200) {
Тоже самое, проверяется аннотацией `@Size`

2023-01-29 17:25 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.warn("Запрос на действие с фильмом длинна описания которого больше 200 символов");       // Не особо понял зачем я это пишу, ведь когда программа выбросит исключение, там будет сообще
Да, предлагаю здесь не логировать, логировать следует когда перехватываешь исключение, а не когда бросаешь

2023-01-29 17:25 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getDuration() <= 0) {
Уже проверяется аннотацией `@Positive`

2023-01-29 17:25 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +}
Те же замечания, что и для фильм-контроллера. Плюс не вижу логики про имя юзера и логин

2023-01-29 17:25 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public void validate(Film film) {
private, тестировать через публичные методы

2023-01-29 17:25 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotBlank
Так как здесь аннотации, лучше отделить поля пустыми линиями, легче читается когда много полей

2023-01-29 17:25 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Size(min = 1, max = 200)
Добавь `@NotNull`, `@Size` на null не проверяет

2023-01-29 17:25 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @PastOrPresent
Добавь `@NotNull`

2023-01-29 17:25 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private String email;
```
@NotBlank
@Email
private String email;
```

2023-01-29 17:25 UTC, kalitva commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +		film.setDescription("ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" +
`"fff".repeat(100);`

2023-01-29 17:25 UTC, kalitva commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	static FilmController filmController = new FilmController();
Форматируй пробелами

2023-02-01 12:30 UTC, kalitva requested changes

2023-02-01 12:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                log.warn("Film with this id was not found");
Предлагаю здесь не логировать

2023-02-01 12:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("Film duration must be positive");  // Сначала удалил такие места где аннотации в model перекрывают эту валидацию, при написании тестов увидел что все таки н
При обычных тестах java bean валидации не будут работать, но будут работать по обращении через http

2023-02-01 12:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            // например тут в тесте я вводил dutation -4 и тест писал что "ожидается исключение ... но никакого исключения нет. Вернул эту валидацию обратно, тест работает
Удали валидацию, дублирующую валидации аннотациями и удали тесты, которые проверяют эти кейсы. Если не ошибаюсь, здесь должна остаться только валидация даты релиза

2023-02-01 12:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName() == null || user.getName().isBlank()) {
Этот блок не является валидацией, перемести его отсюда

2023-02-01 12:30 UTC, kalitva commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +        Exception exception = assertThrows(NullPointerException.class, () -> filmController.addFilm(film));
Никогда не надо тестировать NPE, если он вылетел, это всегда ошибка. Выясни откуда он у тебя там вылетает и поправь

Тестировать необходимо только те исключения, которые мы сами выбрасываем

2023-02-01 16:02 UTC, Vanchey359 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +        Exception exception = assertThrows(NullPointerException.class, () -> filmController.addFilm(film));
NPE вылетает из за того что поля помеченные NotNull не заполнены, странно но эта аннотация почему то в тестах срабатывает "_"

2023-02-02 05:50 UTC, kalitva approved these changes

2023-02-02 05:50 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (films.containsKey(film.getId())) {
Guard clause

```
if (!films.containsKey(film.getId())) {
    throw ...
}
films.put(...
```

https://www.codementor.io/@clintwinter/use-guard-clauses-for-cleaner-code-1rrsczgwxp

2023-02-02 05:50 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (users.containsKey(user.getId())) {
1. Нет вызова `validate`
2. guard clause

2023-02-02 05:50 UTC, kalitva commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    static FilmController filmController = new FilmController();
А почему static?

2023-02-02 05:50 UTC, kalitva commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    void shouldValidateFilmWithOldReleaseDate() {
Сначала должно идти название тестируемого метода

2023-02-02 05:50 UTC, kalitva commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    void shouldValidateUserWithEmptyName() {
`addUserShouldSetLoginToNameIfNameIsEmpty`

2023-02-02 14:34 UTC, merged